### ISSUE TITLE
[TODO_LIST] Première TODO en vue de faire le website

### ISSUE THREAD

**Issue by lduf** [PWEBCICR/website#1]
**Quel est le but de mon issue ?**

Choses à faire :

- [x] Trouver une implémentation minimale du site web en terme de page (un dessin des différentes pages par exemple)
- [x] Extraire les views et templates nécessaires à partir du draft du website
- [x] Extraire les différents controllers nécessaires
- [x] Réfléchir aux routes nécessaires

**Informations supplémentaires**
Si la TODO est obscure : 

- [x] Se renseigner sur Laravel
